### ISSUE TITLE
Delete command deletes directory without checking for an actual Gazelle project

### ISSUE THREAD

**Issue by filippomenchini** [intales/gazelle#32]
## Description
When a developer types `gazelle delete`, the CLI does not check for an actual Gazelle project inside the current directory.
This can lead to an unwanted behaviour: if a developer launches `gazelle delete` in **any** directory, it will **delete**
all of the directory's content.

## Expected behaviour
Whenever a developer launches `gazelle delete` the CLI should search for an actual Gazelle project with the `loadProjectConfiguration` function, if a project is found the user will be prompt to confirm the intent to delete the project,
otherwise the CLI should exit and say that the project was not found.

**Comment by raman04-byte** [comment]
Can you assign this to me.

**Comment by filippomenchini** [comment]
Sure @raman04-byte!
