### ISSUE TITLE
Create handler CLI command

### ISSUE THREAD

**Issue by filippomenchini** [intales/gazelle#33]
It would be nice to have a command like `gazelle create handler` that asks for a `routeName` and a `httpMethod`.
With this information, we could use the `createHandler` function and link the created handler to the `routeName` provided by the developer.

**Comment by filippomenchini** [comment]
@ShivanshuKGupta is actively working on this.

**Comment by raman04-byte** [comment]
I would be better if you assign this task to @ShivanshuKGupta

**Comment by ShivanshuKGupta** [comment]
https://github.com/intales/gazelle/pull/39
