### ISSUE TITLE
Gazelle CLI: Testing

### ISSUE THREAD

**Issue by filippomenchini** [intales/gazelle#52]
The Gazelle CLI works, but it needs some more testing.

## What we should do

We should create tests for every command and common function.
If testing becomes impossible due to coupling, we should try to decouple it.

This would also make the codebase much cleaner and maintainable.

**Comment by raman04-byte** [comment]
I would like to solve this issue.

**Comment by filippomenchini** [comment]
Hello @raman04-byte, feel free to try it!
